city_alpha2 = {
    "Aalborg": "DK",
    "Aarhus": "DK",
    "Abadan": "IR",
    "Abakan": "RU",
    "Aberdeen": "US",
    "Abha": "SA",
    "Abu Dhabi": "AE",
    "Abidjan": "CI",
    "Abilene": "US",
    "Abuja": "NG",
    "Acapulco": "MX",
    "Acarigua": "VE",
    "Accra": "GH",
    "Adak Island": "US",
    "Adana": "TR",
    "Addis Ababa": "ET",
    "Adelaide": "AU",
    "Aden": "YE",
    "Adler": "RU",
    "Agadir": "MA",
    "Aguascaliente": "MX",
    "Ahmedabad": "IN",
    "Ajaccio": "FR",
    "Akiachak": "US",
    "Akiak": "US",
    "Akita": "JP",
    "Akron/Canton": "US",
    "Al-Baha": "SA",
    "Al-Fujairah": "AE",
    "Albany": "US",
    "Albert Bay": "CA",
    "Albuquerque": "US",
    "Aleandroupolis": "GR",
    "Aleppo": "SY",
    "Alexandria": "US",
    "Algiers": "DZ",
    "Alicante": "ES",
    "Allakaket": "US",
    "Allentown": "US",
    "Alma Ata": "KZ",
    "Alor Setar": "MY",
    "Altoona": "US",
    "Amarillo": "US",
    "Amchitka": "US",
    "Amman": "JO",
    "Amritsar": "IN",
    "Amsterdam": "NL",
    "Baghdad": "IQ",
    "Bahrain": "BH",
    "Bakersfield": "US",
    "Bali Island, Denpasar": "ID",
    "Balmaceda": "CL",
    "Baltimore": "US",
    "Bamako": "ML",
    "Bandar Abbas": "IR",
    "Bandar Seri Bagawan": "BN",
    "Bangalore": "IN",
    "Bangkok": "TH",
    "Bangor": "US",
    "Bangui": "CF",
    "Banjul": "GM",
    "Baotou": "CN",
    "Barbados": "BB",
    "Barcelona": "ES",
    "Bardufoss": "NO",
    "Bari": "IT",
    "Barinas": "VE",
    "Barquisimeto": "VE",
    "Barranquilla": "CO",
    "Barrow": "US",
    "Basle": "CH",
    "Basra": "IQ",
    "Bastia": "FR",
    "Baton Rouge": "US",
    "Battle Creek": "US",
    "Bay City/Saginaw": "US",
    "Beaumont": "US",
    "Beaver": "US",
    "Beef Island, Tortola": "VG",
    "Beijing": "CN",
    "Beira": "MZ",
    "Beirut": "LB",
    "Belem": "BR",
    "Belfast": "GB",
    "Belgrade": "RS",
    "Belize": "BZ",
    "Bellingham": "US",
    "Belo Horizonte": "BR",
    "Benghazi": "LY",
    "Bergen": "NO",
    "Berlin": "DE",
    "Bermuda": "BM",
    "Bern": "CH",
    "Bethel": "US",
    "Bettles": "US",
    "Cairns": "AU",
    "Cairo": "EG",
    "Cajamarca": "PE",
    "Calama": "CL",
    "Calcutta": "IN",
    "Calgary": "CA",
    "Cali": "CO",
    "Calicut": "IN",
    "Calvi": "FR",
    "Cambridge Bay": "CA",
    "Campo Grande": "BR",
    "Canaima": "VE",
    "Cancun": "MX",
    "Cape Girardeau": "US",
    "Cape Town": "ZA",
    "Caracas": "VE",
    "Cardiff": "GB",
    "Carlsbad": "US",
    "Cartagena": "CO",
    "Carupano": "VE",
    "Casablanca AAA": "MA",
    "Casablanca, Mohamed V": "MA",
    "Casablanca, Anfa": "MA",
    "Casper": "US",
    "Catania": "IT",
    "Cayenne": "GF",
    "Cebu": "PH",
    "Cedar City": "US",
    "Cedar Rapids / Iowa City": "US",
    "Chachapoyas": "PE",
    "Chalkyits": "US",
    "Champaign": "US",
    "Changchun": "CN",
    "Changsha": "CN",
    "Charleston": "US",
    "Charlotte": "US",
    "Chattanooga": "US",
    "Chefornak": "US",
    "Cheju": "KR",
    "Chengdu": "CN",
    "Chetumal": "MX",
    "Chevak": "US",
    "Chiang Mai": "TH",
    "Chicago": "US",
    "Chichenitza": "MX",
    "Chiclayo": "PE",
    "Chico": "US",
    "Chignik": "US",
    "Chihuahua": "MX",
    "Chisholm": "US",
    "Chittagong": "BD",
    "Dakar": "SN",
    "Dalaman": "TR",
    "Dalian": "CN",
    "Dallas/Ft. Worth": "US",
    "Dallas": "US",
    "Damascus": "SY",
    "Danville": "US",
    "Dar Es Salaam": "TZ",
    "Darwin": "AU",
    "Davao": "PH",
    "Dayton": "US",
    "Daytona Beach": "US",
    "Decatur": "US",
    "Deer Lake": "CA",
    "Delhi": "IN",
    "Delta": "US",
    "Denver": "US",
    "Des Moines": "US",
    "Detroit": "US",
    "Dhahran": "SA",
    "East London": "ZA",
    "East Midlands": "GB",
    "Easter Island": "CL",
    "Edinburgh": "GB",
    "Edmonton": "CA",
    "Eek": "US",
    "Eglin Afb/Valparaiso": "US",
    "Eindhoven": "NL",
    "El Paso": "US",
    "El Salvador": "SV",
    "Elat": "IL",
    "Elko": "US",
    "Ely": "US",
    "Fairbanks": "US",
    "Fall River, New Bedford": "US",
    "False Pass": "US",
    "Fargo": "US",
    "Faro": "PT",
    "Fayetteville": "US",
    "Fez": "MA",
    "Fillmore": "US",
    "Flagstaff": "US",
    "Flint": "US",
    "Florence": "IT",
    "Flores": "GT",
    "Fort Myers": "US",
    "Fort Nelson": "CA",
    "Fort St. John": "CA",
    "Fortaleza": "BR",
    "Gainesvile": "US",
    "Galena": "US",
    "Garoua": "CM",
    "Gassim": "SA",
    "Gauhati": "IN",
    "Gemena": "CD",
    "Geneva": "CH",
    "Genoa": "IT",
    "Glasgow": "GB",
    "Goma": "CD",
    "Goodnew Bay": "US",
    "Goose Bay": "CA",
    "Goroka": "PG",
    "Gothenburg": "SE",
    "Gran Canaria": "ES",
    "Grand Cayman": "KY",
    "Grand Fork": "US",
    "Grand Rapids": "US",
    "Grand Turk": "TC",
    "Grande Prairie": "CA",
    "Grayling": "US",
    "Graz": "AT",
    "Hagen": "DE",
    "Haikou": "CN",
    "Hail": "SA",
    "Hakodate": "JP",
    "Halifax": "CA",
    "Hall Beach": "CA",
    "Hamburg": "DE",
    "Hamilton": "CA",
    "Hampton / Williamsburg": "US",
    "Hangzhou": "CN",
    "Hanoi": "VN",
    "Hanover": "DE",
    "Harare": "ZW",
    "Harbin": "CN",
    "Harlingen": "US",
    "Harrisburg": "US",
    "Hartford": "US",
    "Hat Yai": "TH",
    "Haugesund": "NO",
    "Havana": "CU",
    "Hay River": "CA",
    "Hefei": "CN",
    "Helena": "US",
    "Helsingborg": "SE",
    "Helsinki": "FI",
    "Heraklion": "GR",
    "Hermosillo": "MX",
    "Iguassu Falls": "BR",
    "Iliamna": "US",
    "Indianapolis": "US",
    "Innsbruck": "AT",
    "Inuvik": "CA",
    "Ipoh": "MY",
    "Iqaluit": "CA",
    "Iquique": "CL",
    "Iron Mountain": "US",
    "Isfahan": "IR",
    "Isiro": "CD",
    "Islamabad": "PK",
    "Isles of Scilly, St. Mary’s": "GB",
    "Isles of Scilly, Tresco": "GB",
    "Jackson": "US",
    "Jacksonville": "US",
    "Jaipur": "IN",
    "Jakarta": "ID",
    "Janesville": "US",
    "Jeddah": "SA",
    "Jersey": "JE",
    "Kabul": "AF",
    "Kaduna": "NG",
    "Kagoshima": "JP",
    "Kahului": "US",
    "Kailua": "US",
    "Kalamazoo": "US",
    "Kalispell": "US",
    "Kananga": "CD",
    "Kano": "NG",
    "Kansas City": "US",
    "Kaohsiung": "TW",
    "Karachi": "PK",
    "Karaganda": "KZ",
    "Karup": "DK",
    "Kathmandu": "NP",
    "Kauai Is": "US",
    "Kenai": "US",
    "Kerman": "IR",
    "Ketchikan": "US",
    "Khabarovsk": "RU",
    "Kiev": "UA",
    "Kigali": "RW",
    "Kilimanjaro": "TZ",
    "Killeen": "US",
    "Kimberley": "ZA",
    "Kindu": "CD",
    "La Ceiba": "HN",
    "La Crosse": "US",
    "La Paz": "BO",
    "La Paz Mex": "MX",
    "Labuan": "MY",
    "Lae": "PG",
    "Lafayette": "US",
    "Lagos": "NG",
    "Lahad Datu": "MY",
    "Lahore": "PK",
    "Lake Charles": "US",
    "Lanai City": "US",
    "Langkawi": "MY",
    "Lansing": "US",
    "Lanzhou": "CN",
    "Laredo": "US",
    "Larnaca": "CY",
    "Las Piedras": "VE",
    "Las Vegas": "US",
    "Launceston": "AU",
    "Lawton": "US",
    "Le Havre": "FR",
    "Leeds": "GB",
    "Leipzig": "DE",
    "Lethbridge": "CA",
    "Lhasa": "CN",
    "Libreville": "GA",
    "Liege": "BE",
    "Lille": "FR",
    "Lilongwe": "MW",
    "Lima": "PE",
    "Limoges": "FR",
    "Lincoln": "US",
    "Linz": "AT",
    "Maastricht": "NL",
    "Macon": "US",
    "Madison": "US",
    "Madras": "IN",
    "Madrid": "ES",
    "Magadan": "RU",
    "Mahe Island": "SC",
    "Maiduguri": "NG",
    "Majuro": "MH",
    "Malaga": "ES",
    "Male": "MV",
    "Malmo": "SE",
    "Malongo": "AO",
    "Malta": "MT",
    "Manado": "ID",
    "Managua": "NI",
    "Manaus": "BR",
    "Manchester": "GB",
    "Manila": "PH",
    "Manzanillo": "MX",
    "Maputo": "MZ",
    "Maracaibo": "VE",
    "Maribor": "SI",
    "Marietta, Parkersburg": "US",
    "Marion": "US",
    "Marquette": "US",
    "Marrakech": "MA",
    "Marseille": "FR",
    "Marshall": "US",
    "Martha’s Vineyard": "US",
    "Mashad": "IR",
    "Matamoros": "MX",
    "Matsuyama": "JP",
    "Maturin": "VE",
    "Mauritius": "MU",
    "Mayaguez": "PR",
    "Mazatlan": "MX",
    "Mbandaka": "CD",
    "Mbuji Mayi": "CD",
    "Mc Allen": "US",
    "Mc Grath": "US",
    "Medan": "ID",
    "Medellin": "CO",
    "Medford": "US",
    "Medina": "SA",
    "Meekatharra": "AU",
    "Mekoryuk": "US",
    "Melbourne": "AU",
    "Melbourne, City Heliport": "AU",
    "Melbourne, Essendon": "AU",
    "Memphis": "US",
    "Mendoza": "AR",
    "Merida": "MX",
    "Meridian": "US",
    "Mexico City": "MX",
    "N’djamena": "TD",
    "Nadi": "FJ",
    "Nagasaki": "JP",
    "Nagoya": "JP",
    "Nairobi": "KE",
    "Nanning": "CN",
    "Nantes": "FR",
    "Nantucket": "US",
    "Naples": "IT",
    "Nashville": "US",
    "Nassau": "BS",
    "Natal": "BR",
    "Neuchatel": "CH",
    "New Bern": "US",
    "New Orleans": "US",
    "New York": "US",
    "Newburgh": "US",
    "Newcastle": "GB",
    "Newtok": "US",
    "Oakland": "US",
    "Oaxaca": "MX",
    "Oita": "JP",
    "Okayama": "JP",
    "Okinawa": "JP",
    "Oklahoma City": "US",
    "Omaha": "US",
    "Ontario": "US",
    "Oran": "DZ",
    "Orebro": "SE",
    "Orlando": "US",
    "Osaka": "JP",
    "Pago Pago": "AS",
    "Palembang": "ID",
    "Palermo": "IT",
    "Palm Springs": "US",
    "Palma de Mallorca": "ES",
    "Panama City": "PA",
    "Papeete": "PF",
    "Paphos": "CY",
    "Paramaribo": "SR",
    "Paris": "FR",
    "Pasco": "US",
    "Pau": "FR",
    "Penang": "MY",
    "Pensacola": "US",
    "Peoria": "US",
    "Pereira": "CO",
    "Perpignan": "FR",
    "Perth": "AU",
    "Pescara": "IT",
    "Peshawar": "PK",
    "Philadelphia": "US",
    "Phnom Penh": "KH",
    "Phoenix": "US",
    "Phuket": "TH",
    "Pierre": "US",
    "Pisa": "IT",
    "Pittsburgh": "US",
    "Piura": "PE",
    "Platinum": "US",
    "Pocatello": "US",
    "Pohnpei": "FM",
    "Point à Pitre": "GP",
    "Pointe Noire": "CG",
    "Qingdao": "CN",
    "Quebec": "CA",
    "Quetta": "PK",
    "Rabat": "MA",
    "Rabaul": "PG",
    "Raleigh/Durham": "US",
    "Rangoon/Yangon": "MM",
    "Rapid City": "US",
    "Rarotonga": "CK",
    "Recife": "BR",
    "Red Devil": "US",
    "Redding": "US",
    "Regina": "CA",
    "Reno": "US",
    "Resolute": "CA",
    "Reykjavik": "IS",
    "Richmond": "US",
    "Riga": "LV",
    "Rimini": "IT",
    "Rio de Janeiro": "BR",
    "Rio Gallegos": "AR",
    "Riyadh": "SA",
    "Saarbruecken": "DE",
    "Sacramento": "US",
    "Saipan": "MP",
    "Sal": "CV",
    "Salt Lake City": "US",
    "Saltillo": "MX",
    "Salvador": "BR",
    "Salzburg": "AT",
    "San Andres Island": "CO",
    "San Angelo": "US",
    "San Antonio": "US",
    "San Diego": "US",
    "San Francisco": "US",
    "San Jose": "US",
    "San Juan": "PR",
    "San Luis Potosi": "MX",
    "San Pedro Sula": "HN",
    "San Salvador": "SV",
    "San Tome": "VE",
    "Sanaa": "YE",
    "Sand Point": "US",
    "Sandakan": "MY",
    "Santa Barbara": "US",
    "Santa Cruz": "BO",
    "Santa Maria": "US",
    "Santiago": "CL",
    "Santiago de Compostela": "ES",
    "Santo Domingo": "DO",
    "Sanya": "CN",
    "Sao Luiz": "BR",
    "Sao Paulo": "BR",
    "Sao Tome Island": "ST",
    "Sapporo": "JP",
    "Sarasota/Bradenton": "US",
    "Sault Ste. Marie": "CA",
    "Savannah": "US",
    "Scammon Bay": "US",
    "Scranton, Wilkes-Barre": "US",
    "Seattle": "US",
    "Sedona": "US",
    "Seldovia": "US",
    "Sendai": "JP",
    "Seoul": "KR",
    "Sepulot": "MY",
    "Seville": "ES",
    "Seward": "US",
    "Shageluk": "US",
    "Shanghai": "CN",
    "Tabriz": "IR",
    "Tabuk": "SA",
    "Tacna": "PE",
    "Taegu, Korea": "KR",
    "Taichung": "TW",
    "Taif": "SA",
    "Taipei": "TW",
    "Taiyuan": "CN",
    "Takamatsu": "JP",
    "Talara": "PE",
    "Tallahassee": "US",
    "Tallinn": "EE",
    "Tamanrasset": "DZ",
    "Tampa": "US",
    "Tampere": "FI",
    "Tanana": "US",
    "Tangier": "MA",
    "Tarapoto": "PE",
    "Tashkent": "UZ",
    "Tawau": "MY",
    "Teesside": "GB",
    "Tegucigalpa": "HN",
    "Tehran": "IR",
    "Tel Aviv Yafo, Sde Dov": "IL",
    "Tel Aviv Yafo, Tel Aviv": "IL",
    "Temuco": "CL",
    "Tenerife": "ES",
    "Terceira": "PT",
    "Terrace": "CA",
    "Texarkana": "US",
    "Thessaloniki": "GR",
    "Thunder Bay": "CA",
    "Tianjin": "CN",
    "Tijuana": "MX",
    "Timisoara": "RO",
    "Tingo Maria": "PE",
    "Ube": "JP",
    "Ukiah": "US",
    "Ulan Bator": "MN",
    "Vaasa": "FI",
    "Valdosta": "US",
    "Valencia": "ES",
    "Valera": "VE",
    "Valladolid": "ES",
    "Vancouver": "CA",
    "Vasteras": "SE",
    "Vaxjo": "SE",
    "Venetie": "US",
    "Venice": "IT",
    "Wabush": "CA",
    "Waco": "US",
    "Warsaw": "PL",
    "Washington": "US",
    "Watson Lake": "CA",
    "Wausau": "US",
    "Wellington": "NZ",
    "Wenatchee": "US",
    "West Palm Beach": "US",
    "Westchester": "US",
    "Xiamen": "CN",
    "Yakima": "US",
    "Yakutat": "US",
    "Yamagata": "JP",
    "Yantai": "CN",
    "Yap Caroline Island": "FM",
    "Zacatecas": "MX",
    "Zagreb": "HR",
    "Zahedan": "IR",
    "Zanzibar": "TZ",
    "Anchorage": "US",
    "Anchorage, Merrill Field": "US",
    "Ancona": "IT",
    "Andahuaylas": "PE",
    "Anguilla": "AI",
    "Aniak": "US",
    "Ankang": "CN",
    "Ankara": "TR",
    "Ankara, Esenboga": "TR",
    "Annecy": "FR",
    "Antalya": "TR",
    "Antananarivo": "MG",
    "Antigua": "AG",
    "Antofagasta": "CL",
    "Antwerp": "BE",
    "Anvik": "US",
    "Aomori": "JP",
    "Apia": "WS",
    "Appleton": "US",
    "Aqaba": "JO",
    "Arcata, Eureka": "US",
    "Arctic Village": "US",
    "Arecibo": "PR",
    "Arequipa": "PE",
    "Arica": "CL",
    "Aruba": "AW",
    "Ascension": "SH",
    "Asheville": "US",
    "Ashikawa": "JP",
    "Ashland, Huntington": "US",
    "Asmara": "ER",
    "Asturias": "ES",
    "Asuncion": "PY",
    "Aswan": "EG",
    "Athens": "GR",
    "Atlanta": "US",
    "Atlanta, Beaver Ruin": "US",
    "Atlanta, Perimeter": "US",
    "Atlantic City": "US",
    "Atlantic City, Pomona Field": "US",
    "Atmautluak": "US",
    "Auckland": "NZ",
    "Augusta": "US",
    "Austin": "US",
    "Ayacucho": "PE",
    "Biak": "ID",
    "Biarritz": "FR",
    "Bilbao": "ES",
    "Billings": "US",
    "Billund": "DK",
    "Binghamton": "US",
    "Bintulu": "MY",
    "Birmingham": "US",
    "Bissau": "GW",
    "Blantyre": "MW",
    "Bloemfontein": "ZA",
    "Bloomington": "US",
    "Boa Vista": "BR",
    "Bodo": "NO",
    "Bogota": "CO",
    "Boise": "US",
    "Bologna": "IT",
    "Bombay": "IN",
    "Bonaire": "BQ",
    "Bordeaux": "FR",
    "Boston": "US",
    "Boulder": "US",
    "Bourlamaq/Val D’or": "CA",
    "Bournemouth": "GB",
    "Bozeman": "US",
    "Bradley": "US",
    "Brainerd": "US",
    "Brasilia": "BR",
    "Bratislava": "SK",
    "Brazzaville": "CG",
    "Bremen": "DE",
    "Brest": "FR",
    "Bridgeport": "US",
    "Brisbane": "AU",
    "Bristol": "GB",
    "Brownsville": "US",
    "Brussels": "BE",
    "Bucaramanga": "CO",
    "Bucharest": "RO",
    "Budapest": "HU",
    "Buenos Aires": "AR",
    "Bujumbura": "BI",
    "Bulawayo": "ZW",
    "Burbank": "US",
    "Burlington": "US",
    "Bushehr": "IR",
    "Butte": "US",
    "Chongqing": "CN",
    "Christchurch": "NZ",
    "Chuathbaluk": "US",
    "Cincinnati": "US",
    "Ciudad Del Carmen": "MX",
    "Cleveland": "US",
    "Cochabamba": "BO",
    "Cochin": "IN",
    "Coeur D’Alene": "US",
    "Cold Bay": "US",
    "Colima": "MX",
    "College Station": "US",
    "Cologne": "DE",
    "Colombo": "LK",
    "Colorado Springs": "US",
    "Columbia": "US",
    "Columbus": "US",
    "Conakry": "GN",
    "Concepcion": "CL",
    "Copenhagen": "DK",
    "Copiapo": "CL",
    "Cordova": "US",
    "Cork": "IE",
    "Corning, Elmira": "US",
    "Coro": "VE",
    "Corpus Christie": "US",
    "Cotonou": "BJ",
    "Coyhaique": "CL",
    "Cozumel": "MX",
    "Crokked Creek": "US",
    "Cruzeiro Do Sul": "BR",
    "Cuenca": "EC",
    "Cuiaba": "BR",
    "Culebra": "PR",
    "Culiacan": "MX",
    "Cumana": "VE",
    "Curacao": "CW",
    "Curitiba": "BR",
    "Cusco": "PE",
    "Detroit": "US",
    "Detroit City": "US",
    "Dhahran": "SA",
    "Dhaka": "BD",
    "Dillingham": "US",
    "Djerba": "TN",
    "Djibouti": "DJ",
    "Doha": "QA",
    "Dominica, Cane Field": "DM",
    "Dominica, Melville Hall": "DM",
    "Dothan": "US",
    "Douala": "CM",
    "Dresden": "DE",
    "Dubai": "AE",
    "Dublin": "IE",
    "Duluth": "US",
    "Durango": "MX",
    "Durban": "ZA",
    "Dusseldorf": "DE",
    "Dutch Harbor": "US",
    "Enschede": "NL",
    "Entebbe": "UG",
    "Ercan": "CY",
    "Erevan": "AM",
    "Erfurt": "DE",
    "Erie": "US",
    "Eugene": "US",
    "Evansville": "US",
    "Evenes": "NO",
    "Exeter": "GB",
    "Frankfurt": "DE",
    "Fredericton": "CA",
    "Freeport": "BS",
    "Freetown": "SL",
    "Fresno": "US",
    "Friedrichshafen": "DE",
    "Ft de France": "MQ",
    "Ft Pierce": "US",
    "Ft Simpson": "CA",
    "Ft Smith": "US",
    "Ft Wayne": "US",
    "Ft Yukon": "US",
    "Fukuoka": "JP",
    "Funchal": "PT",
    "Fuzhou": "CN",
    "Great Falls": "US",
    "Green Bay": "US",
    "Greensboro": "US",
    "Greenville": "US",
    "Grenada": "GD",
    "Grenoble": "FR",
    "Groningen": "NL",
    "Guadalajara": "MX",
    "Guam": "GU",
    "Guangzhou": "CN",
    "Guatemala City": "GT",
    "Guayaquil": "EC",
    "Guernsey": "GG",
    "Guilin": "CN",
    "Guiyang": "CN",
    "Gulfport": "US",
    "Gunnison": "US",
    "Hilo": "US",
    "Hiroshima": "JP",
    "Ho Chi Minh City": "VN",
    "Hohhot": "CN",
    "Holy Cross": "US",
    "Homer": "US",
    "Hong Kong": "HK",
    "Honolulu": "US",
    "Hoolehua": "US",
    "Hooper Bay": "US",
    "Hoskins": "PG",
    "Houston": "US",
    "Houston, Intercontinental": "US",
    "Houston, Hull Field": "US",
    "Hughes": "US",
    "Humberside": "GB",
    "Huntsville": "US",
    "Huslia": "US",
    "Hyannis": "US",
    "Hyderabad": "IN",
    "Istanbul": "TR",
    "Islip, Long Island Macarthur": "US",
    "Ithaca": "US",
    "Ivano Bay": "US",
    "Izmir": "TR",
    "Izmir, Adnan Menderes": "TR",
    "Izmir, Cigli Military": "TR",
    "Jinan": "CN",
    "Johannesburg": "ZA",
    "Johnston Island": "UM",
    "Johor Bahru": "MY",
    "Jonkoping": "SE",
    "Juanjui": "PE",
    "Juba": "SS",
    "Juliaca": "PE",
    "Juneau": "US",
    "King Cove": "US",
    "King Salm": "AKN",
    "Kingston": "KIN",
    "Kingston, Tinson": "KTP",
    "Kinshasa": "FIH",
    "Kipnuk": "KPN",
    "Kiruna": "KRN",
    "Kisangani": "FKI",
    "Klagenfurt": "KLU",
    "Knoxville": "TYS",
    "Kochi": "KCZ",
    "Kodiak": "ADQ",
    "Komatsu": "KMQ",
    "Kongiganak": "KKH",
    "Koror": "ROR",
    "Kosrae": "KSA",
    "Kota Kinabalu": "BKI",
    "Kotzebue": "OTZ",
    "Koyukuk": "KYU",
    "Krasnoyarsk": "KJA",
    "Kristiansand": "KRS",
    "Kuala Lumpur": "KUL",
    "Kuching": "KCH",
    "Kumamoto": "KMJ",
    "Kunming": "KMG",
    "Kuopio": "KUO",
    "Kushiro": "KUH",
    "Kuujjuarap": "YGW",
    "Kuwait": "KWI",
    "Kwajalein": "KWA",
    "Kwangju": "KWJ",
    "Kwethluk": "KWT",
    "Kwigillingok": "KWK",
    "Lisbon": "LIS",
    "Little Rock": "LIT",
    "Liverpool": "LPL",
    "Livingstone": "LVI",
    "Ljubljana": "LJU",
    "Lobito": "LOB",
    "Lome": "LFW",
    "London": "LON",
    "London, Gatwick": "LGW",
    "London, Heathrow": "LHR",
    "London, City Airport": "LCY",
    "London, Luton": "LTN",
    "London, Stansted": "STN",
    "Long Beach": "LGB",
    "Loreto": "LTO",
    "Los Angeles": "LAX",
    "Los Mochis": "LMM",
    "Louisville": "SDF",
    "Lourdes/Tarbes": "LDE",
    "Luanda": "LAD",
    "Lubbock": "LBB",
    "Lubumbashi": "FBM",
    "Lucknow": "LKO",
    "Ludwigshafen": "LUD",
    "Lugano": "LUG",
    "Lulea": "LLA",
    "Lumid Pau": "LUB",
    "Lusaka": "LUN",
    "Luxembourg": "LUX",
    "Luxor": "LXR",
    "Lyon": "LYS",
    "Miami": "MIA",
    "Midland": "MAF",
    "Milan": "MIL",
    "Milford": "MLF",
    "Milwaukee": "MKE",
    "Minatitlan": "MTT",
    "Minneapolis": "MSP",
    "Minot": "MOT",
    "Minsk": "MSQ",
    "Miri": "MYY",
    "Missoula": "MSO",
    "Miyazaki": "KMI",
    "Mobile": "MOB",
    "Moline": "MLI",
    "Mombasa": "MBA",
    "Moncton": "YQM",
    "Monroe": "MLU",
    "Monrovia": "MLW",
    "Montego Bay": "MBJ",
    "Monterrey": "MTY",
    "Montevideo": "MVD",
    "Montgomery": "MGM",
    "Montpellier": "MPL",
    "Montreal": "YMQ",
    "Morelia": "MLM",
    "Moroni": "YVA",
    "Moscow": "MOW",
    "Mount Hagen": "HGU",
    "Muenster": "FMO",
    "Mulhouse": "MLH",
    "Munich": "MUC",
    "Muscat": "MCT",
    "Muskegon": "MKG",
    "Myrtle Beach": "MYR",
    "Niagara Falls": "IAG",
    "Niamey": "NIM",
    "Nice": "NCE",
    "Nightmute": "NME",
    "Niigata": "KIJ",
    "Nimes": "FNI",
    "Ningbo": "NGB",
    "Nis": "INI",
    "Nome": "OME",
    "Norfolk": "ORF",
    "Norilsk": "NSK",
    "Norman Wells": "YVQ",
    "Norrkoping": "NRK",
    "Norwich": "NWI",
    "Nouakchott": "NKC",
    "Noumea": "NOU",
    "Novosibirsk": "OVB",
    "Nuevo Laredo": "NLD",
    "Nulato": "NUL",
    "Nunapitchuk": "NUP",
    "Nuremberg": "NUE",
    "Osaka": "OSA",
    "Oshkosh": "OSH",
    "Osijek": "OSI",
    "Oslo": "OSL",
    "Osorno": "ZOS",
    "Ostend": "OST",
    "Ottawa": "YOW",
    "Ouagadougou": "OUA",
    "Oxnard/Ventura": "OXR",
    "Ponce": "PSE",
    "Ponta Delgada": "PDL",
    "Pori": "POR",
    "Porlamar": "PMV",
    "Port au Prince": "PAP",
    "Port Elizabeth": "PLZ",
    "Port Gentil": "POG",
    "Port Graham": "PGM",
    "Port Harcourt": "PHC",
    "Port Hedland": "PHE",
    "Port Heiden": "PTH",
    "Port Moresby": "POM",
    "Port of Spain": "POS",
    "Port Velho": "PVH",
    "Port Vila": "VLI",
    "Portland": "PDX",
    "Porto": "OPO",
    "Porto Alegre": "POA",
    "Prague": "PRG",
    "Presque Isle": "PQI",
    "Prince George": "YXS",
    "Prince Rupert": "YPR",
    "Providence": "PVD",
    "Providenciales": "PLS",
    "Prudhoe Bay / Deadhorse": "SCC",
    "Pucallpa": "PCL",
    "Puebla": "PBC",
    "Puerto Ayachucho": "PYH",
    "Puerto Cabello": "PBL",
    "Puerto Escondido": "PXM",
    "Puerto Maldonado": "PEM",
    "Puerto Montt": "PMC",
    "Puerto Ordaz": "PZO",
    "Puerto Plata": "POP",
    "Puerto Vallarta": "PVR",
    "Punta Arenas": "PUQ",
    "Pusan": "PUS",
    "Pyongyang": "FNJ",
    "Quinhagak": "KWN",
    "Quito": "UIO",
    "Roanoke": "ROA",
    "Roatan": "RTB",
    "Rochester": "ROC",
    "Rockford": "RFD",
    "Rocky Mount/Wilson": "RWI",
    "Rome": "ROM",
    "Roosevelt": "ROL",
    "Roswell": "ROW",
    "Rota": "ROP",
    "Rotterdam": "RTM",
    "Rouen": "URO",
    "Ruby": "RBY",
    "Shannon": "SNN",
    "Shantou/Swatow": "SWA",
    "Sharjah": "SHJ",
    "Shemya Islands": "SYA",
    "Shenyang": "SHE",
    "Shenzhen": "SZX",
    "Shetland Islands": "LWK",
    "Shijiazhuang": "SJW",
    "Shiraz": "SYZ",
    "Shreveport": "SHV",
    "Sibu": "SBW",
    "Simferopol": "SIP",
    "Singapore": "SIN",
    "Sioux Falls": "FSD",
    "Sitka": "SIT",
    "Sofia": "SOF",
    "Sokoto": "SKO",
    "Soldotna": "SXQ",
    "Sonderborg": "SGD",
    "Sondre Stromord": "SFJ",
    "South Bend": "SBN",
    "Springfield": "SGF",
    "St. Denis de La Reunion": "RUN",
    "St. George": "SGU",
    "St. George Island": "STG",
    "St. Johns": "YYT",
    "St. Kitts": "SKB",
    "St. Louis": "STL",
    "St. Lucia": "SLU",
    "St. Maarten": "SXM",
    "St. Mary’s": "KSM",
    "St. Petersburg": "LED",
    "St. Thomas": "STT",
    "St. Vincent": "SVD",
    "Stavanger": "SVG",
    "Steamboat Springs": "SBS",
    "Stevens Village": "SVS",
    "Stockholm": "STO",
    "Stockton": "SCK",
    "Stony River": "SRV",
    "Strasbourg": "SXB",
    "Stuttgart": "STR",
    "Sudbury": "YSB",
    "Sukhumi": "SUI",
    "Sundsvall": "SDL",
    "Surabaya": "SUB",
    "Suva": "SUV",
    "Sydney": "SYD",
    "Syracuse": "SYR",
    "Tobago": "TAB",
    "Toksook Bay": "OOK",
    "Tokushima": "TKS",
    "Tokyo": "TYO",
    "Toledo": "TOL",
    "Tongatapu": "TBU",
    "Topeka": "TOP",
    "Toronto": "YTO",
    "Torreon": "TRC",
    "Tottori": "TTJ",
    "Toulon/Hyeres": "TLN",
    "Toulouse": "TLS",
    "Toyama": "TOY",
    "Traverse City": "TVC",
    "Trenton": "TTN",
    "Tri-City": "TRI",
    "Trieste": "TRS",
    "Tripoli": "TIP",
    "Trivandrum": "TRV",
    "Trombetas": "TMT",
    "Tromso": "TOS",
    "Trondheim": "TRD",
    "Trujillo": "TRU",
    "Truk": "TKK",
    "Tucson": "TUS",
    "Tulsa": "TUL",
    "Tuluksak": "TLT",
    "Tumbes": "TBP",
    "Tunis": "TUN",
    "Tuntutulia": "WTL",
    "Tununak": "TNK",
    "Turin": "TRN",
    "Turku": "TKU",
    "Tuscaloosa": "TCL",
    "Tuxtla Gutierrez": "TGZ",
    "Twin Falls": "TWF",
    "Tyler": "TYR",
    "Umea": "UME",
    "Unalakleet": "UNK",
    "Urumqi": "URC",
    "Veracruz": "VER",
    "Vernal": "VEL",
    "Verona": "VRN",
    "Victoria": "YYJ",
    "Vienna": "VIE",
    "Vientiane": "VTE",
    "Vieques": "VQS",
    "Villahermosa": "VSA",
    "Vilnius": "VNO",
    "Vitoria": "VIT",
    "Vladivostok": "VVO",
    "White River": "LEB",
    "Whitehorse": "YXY",
    "Wichita": "ICT",
    "Wichita Falls": "SPS",
    "Wilmington": "ILM",
    "Windhoek": "WDH",
    "Windsor": "YQG",
    "Winnipeg": "YWG",
    "Wrangell": "WRG",
    "Wuhan": "WUH",
    "Xian": "SIA",
    "Yellowknife": "YZF",
    "Yinchuang": "INC",
    "Yurimaguas": "YMS",
    "Yuzhno-Sakhalinsk": "UUS",
    "Zhanjiang": "ZHA",
    "Zhengzhou": "CGO",
    "Zihuatanejo": "ZIH",
    "Zurich": "ZRH"
}
